### ISSUE TITLE
Missing attribution

### ISSUE THREAD

**Issue by ddevault** [3ventic/TwitchChatSharp#2]
Hi there! This project needs to correctly attribute the upstream source (me). Easy change would be to add this line to your LICENSE file:

```
Copyright (c) 2016 Drew DeVault
```

Right next to your own copyright line.

Thanks!

**Comment by 3ventic** [comment]
There is no upstream. I wrote all of this independently. What are you referring to?

**Comment by ddevault** [comment]
I may be mistaken. Looking through the code and the title of the repo I guessed that it was a derivative of [ChatSharp](https://github.com/SirCmpwn/ChatSharp). If that's not the case, then disregard this.

**Comment by 3ventic** [comment]
Ah, just an unfortunate naming on my part it seems. This was all written from scratch over the last ~2 years as a part of another project and recently split into a standalone version.

**Comment by ddevault** [comment]
No worries, thanks for clarifying!
